### ISSUE TITLE
Epic: CI for all supported K8s versions

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner#1102]
**What would you like to be added**:

Each K8s version supported by the upcoming release should be tested by CI.

**Why is this needed**:

As we move towards slower, more stable releases, we should be clear about which K8s versions will be supported by the next release.

**TODOs**:

- [x] Update KIND to support deploying with newer K8s versions.
  * [x] https://github.com/submariner-io/shipyard/pull/466
- [x] Expose `k8s_version` `clusters.sh` flag via `using=` flag and E2E/upgrade GHAs in Shipyard.
  * [x] https://github.com/submariner-io/shipyard/pull/485
  * [x] https://github.com/submariner-io/shipyard/pull/486
  * [x] https://github.com/submariner-io/shipyard/pull/487
- [x] Add debugging info for K8s version.
  * [x] https://github.com/submariner-io/shipyard/pull/498
- [x] Test all supported K8s versions at least once in Shipyard's Consuming Projects E2E.
  * [x] https://github.com/submariner-io/shipyard/pull/496
- [ ] Add `k8s_version` to E2E GHA matrix in each repo.
  * [x] Develop agreement on minimal test matrix. (result: https://github.com/submariner-io/submariner/pull/1242)
  * [ ] https://github.com/submariner-io/submariner/pull/1241
  * Alternatives:
    * [x] https://github.com/submariner-io/submariner/pull/1214
    * [x] https://github.com/submariner-io/submariner/pull/1242
  * [x] https://github.com/submariner-io/submariner-operator/pull/1183
  * [x] https://github.com/submariner-io/submariner-operator/pull/1245
  * [x] https://github.com/submariner-io/lighthouse/pull/495
  * [x] https://github.com/submariner-io/submariner-charts/pull/130
  * [ ] Parallel the matrix for each repo in Shipyard's Consuming Projects tests.
- [ ] Add `k8s_version` to periodic E2E GHA matrix in appropriate repos.
  * [ ] Develop agreement on larger test matrix.
  * [x] https://github.com/submariner-io/submariner-operator/pull/1184
  * [x] https://github.com/submariner-io/lighthouse/pull/503
  * [x] https://github.com/submariner-io/submariner-operator/pull/1248
- [ ] Fix issues with newer K8s versions
  * [x] Globalnet+1.20 flakiness: https://github.com/submariner-io/shipyard/pull/530
- [ ] **Make the default K8s version equal the latest K8s version.**

**Nice-to-have**: 

- [ ] Test a mix of clusters using all supported K8s versions.
  * [ ] Ability to configure K8s version per-cluster from the Shipyard E2E GHA?
- [ ] Upgrade/test through all supported K8s versions.

**Comment by dfarrell07** [comment]
It seems we should try to support K8s versions 1.19, 1.20. and 1.21 (current latest).

**Comment by dfarrell07** [comment]
We may also want to test a mix and match of version among clusters.

**Comment by dfarrell07** [comment]
Depends on updating KIND to a newer version: https://github.com/submariner-io/shipyard/pull/353, https://github.com/submariner-io/shipyard/pull/466

**Comment by nyechiel** [comment]
@dfarrell07 can you turn this Issue into an "Epic" and break it down into individual tasks we can track for 0.9? Thanks!

**Comment by dfarrell07** [comment]
The main thing still remaining for this epic is moving the version of K8s we build against from 1.17 to 1.20. We can then make the final tweaks to GHA configurations for best coverage with minimal load.

**Comment by nyechiel** [comment]
> The main thing still remaining for this epic is moving the version of K8s we build against from 1.17 to 1.20. We can then make the final tweaks to GHA configurations for best coverage with minimal load.

Thanks @dfarrell07. I suggest to track that separately and close this epic at this point.

**Comment by skitt** [comment]
I just opened https://github.com/submariner-io/submariner/issues/1298 for different reasons but it is related to this effort (and 1.20 is probably too new for us...).

**Comment by dfarrell07** [comment]
> > The main thing still remaining for this epic is moving the version of K8s we build against from 1.17 to 1.20. We can then make the final tweaks to GHA configurations for best coverage with minimal load.
> 
> Thanks @dfarrell07. I suggest to track that separately and close this epic at this point.

Okay, makes sense. Moving to 1.19 is tracked by @skitt's https://github.com/submariner-io/submariner/issues/1298 and we'll likely always be tweaking GHA matrixes for the needs of the moment.
