### ISSUE TITLE
Epic: Proper NAT support for all combinations

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner#1174]
**What would you like to be added**:

### Automatic NAT/NO-NAT discovery between two endpoints (fix https://github.com/submariner-io/submariner/issues/300 )
* [x] (#1175) Define protocol (see goals of the protocol in the issue), select a port number
* [x] (#1176) Implement protocol pkg + testing
* [x] (#1177) Implement in gateways

### Individual port assignments to gateways
 * [x] (#1178) (Expose the cabledriver gateway ports on the Endpoint information
 * [x] (#1179) Allow IPSec port selection with labels see #1146 code for reference
 
### Additional work
* [x] (#1224) Support client/server model for IPSec
* [x] Support enforcement of UDP encapsulation for environments where NAT is not detected, but ESP/AH is not supported.

**Why is this needed**:

With a mix of on-prem & on-cloud deployments the current global nat/no-nat doesn't work. Also from the point of view of HA, such NAT support would also require individual port numbers for each gateway node. See https://github.com/submariner-io/submariner/issues/300
