### ISSUE TITLE
CNCF Sandbox Onboarding

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner#1297]
[Submariner's CNCF Sandbox application](https://docs.google.com/document/d/173OMp7GgDkK6trUqL1FPNkwRVDD1dTe9Z3-XmIoJhiI) was [accepted by the CNCF TOC](https://www.youtube.com/watch?v=2u9weuhEh4c)! :partying_face: We now need to complete the Sandbox onboarding process.

We need to show our results on the TOC's Issue (https://github.com/cncf/sandbox/issues/244). I've copied the chunks that need action from us, so we can add details and collectively edit to check boxes/add lines.

Read:

Should all the [Project Owners](https://github.com/orgs/submariner-io/teams/submariner-owners/members) + me (CNCF driver) review these and ACK?

- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction
  - [x] @dfarrell07
  - [x] @skitt
  - [x]  @tpantelis 
  - [x] @mangelajo
  - [x] Resulting requirement: "List their sandbox status prominently on website/readme" in the [Sandbox criteria](https://github.com/cncf/toc/blob/main/process/graduation_criteria.adoc#sandbox-stage)
    - [x] https://github.com/submariner-io/submariner/pull/1349
    - [x] https://github.com/submariner-io/submariner-website/pull/517
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
  - [x] @dfarrell07
  - [x] @skitt
  - [x]  @tpantelis
  - [x] @mangelajo
- [x] Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
  - [x] @dfarrell07
  - [x] @skitt
  - [x]  @tpantelis
  - [x] @mangelajo
- [x] Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/
  - [x] @dfarrell07
  - [x] @skitt
  - [x]  @tpantelis
  - [x] @mangelajo

Do:

- [x] Has your project adopted open governance already? see http://opengovernance.dev
  - We have https://submariner.io/community/contributor-roles/ (based on K8s governance), but we should add GOVERNCE.md files and maybe adopt other good practices from the examples provided in the TOC's PR.
  - [x] Add GOVERNANCE.md, answer open gov checklist https://github.com/submariner-io/submariner/pull/1327
  - [x] Document participants in security disclosures https://github.com/submariner-io/submariner-website/pull/518
  - [x] Add Project Owner responsibilities https://github.com/submariner-io/submariner-website/pull/520
  - [x] Update Owner removal docs in governance summary https://github.com/submariner-io/submariner/pull/1391
- [x] CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en
  - [x] Achieve CII Passing status https://github.com/submariner-io/submariner/issues/798
    - https://bestpractices.coreinfrastructure.org/en/projects/4865
  - [x] Document test policy for CII Best Practices https://github.com/submariner-io/submariner-website/pull/515
issues
  - [x] Add CII badges
    - [x] https://github.com/submariner-io/submariner/pull/1343
    - [x] https://github.com/submariner-io/submariner-operator/pull/1370
    - [x] https://github.com/submariner-io/admiral/pull/221
    - [x] https://github.com/submariner-io/enhancements/pull/31
    - [x] https://github.com/submariner-io/lighthouse/pull/538
    - [x] https://github.com/submariner-io/releases/pull/140
    - [x] https://github.com/submariner-io/shipyard/pull/559
    - [x] https://github.com/submariner-io/submariner-charts/pull/142
    - [x] https://github.com/submariner-io/cloud-prepare/pull/44
  - [x] Add pull request template
    - [x] https://github.com/submariner-io/submariner/pull/1342
    - [x] https://github.com/submariner-io/submariner-operator/pull/1372
    - [x] https://github.com/submariner-io/submariner-charts/pull/143
    - [x] https://github.com/submariner-io/shipyard/pull/561
    - [x] https://github.com/submariner-io/releases/pull/142
    - [x] https://github.com/submariner-io/lighthouse/pull/541
    - [x] https://github.com/submariner-io/coastguard/pull/28
    - [x] https://github.com/submariner-io/admiral/pull/223
    - [x] https://github.com/submariner-io/cloud-prepare/pull/45
- [x] Domain: transfer domain to the CNCF - please send a transfer code to amye@linuxfoundation.org
  - @Oats87 is working on getting transfer code sent to @amye.
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements
  - @Oats87 is working on the trademark transfer agreement.
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
  - Now that we’ve switched to a paid plan, this requires buying more user capacity
  - [Org Owners](https://github.com/orgs/submariner-io/teams/submariner-owners/members)
  - [x] caniszczyk
  - [x] thelinuxfoundation
- [x] Artwork: Ensure logos present on https://github.com/cncf/artwork
  - [x] Create 18 SubM logos versions for cncf/artwork https://github.com/submariner-io/submariner/issues/1311
  - [x] https://github.com/cncf/artwork/pull/250
  - [x] https://github.com/cncf/artwork/pull/251
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) ([corrected link](https://github.com/cncf/foundation/blob/master/website-guidelines.md) from OP) followed
   - [x]  If there is a copyright notice at the bottom of the page, copyright should be to the project authors or to CNCF, not the origin company. For details, see Copyright notices.
     - [x] Add copyright notice to footer https://github.com/submariner-io/submariner-website/pull/516
  - [x] "CNCF requests that graduated and incubating projects include the sentence “We are a Cloud Native Computing Foundation project.” and the CNCF logo near the bottom of their project homepage. Sandbox-level projects should include the sentence “We are a Cloud Native Computing Foundation sandbox project.” and the CNCF logo. We also appreciate a link to KubeCon + CloudNativeCon as the events approach."
    - [x] https://github.com/submariner-io/submariner-website/pull/517
    - [x] https://github.com/submariner-io/submariner-website/pull/523
  - [x] "Website footers must include trademark guidelines by either linking to Trademark Usage (directly or via a "Terms of service" page), or by including the following text: "The Linux Foundation® (TLF) has registered trademarks and uses trademarks. For a list of TLF trademarks, see Trademark Usage"."
    - [x] https://github.com/submariner-io/submariner-website/pull/522
- [x] Code copyright notices (not listed in requirements but should be?)
    - [x] Change Copyright Notices to CNCF-recommended format https://github.com/submariner-io/submariner/issues/1322 
    - [x] Update the copyright statements to match CNCF recs
      - [x] https://github.com/submariner-io/submariner/pull/1335
      - [x] https://github.com/submariner-io/submariner-operator/pull/1373
      - [x] https://github.com/submariner-io/lighthouse/pull/539
      - [x] https://github.com/submariner-io/admiral/pull/224
      - [x] https://github.com/submariner-io/cloud-prepare/pull/46
      - [x] https://github.com/submariner-io/shipyard/pull/558
- [x] Website: Analytics transferred to amye@linuxfoundation.org
  - I don't think we have any sort of analytics.
- [x] Adopt a license scanning tool, like FOSSA or Snyk
  - [x] Add dependency license scanning linting https://github.com/submariner-io/submariner/issues/801
  - [x] Add a license-checking job
    - [x] https://github.com/submariner-io/submariner/pull/1326
    - [x] https://github.com/submariner-io/submariner-operator/pull/1366
    - [x] https://github.com/submariner-io/lighthouse/pull/537
  - [x] Don't use `go-ipify`
- [x] Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io
  - This should likely be one of the last steps.
  - Cloud Native Networking section https://landscape.cncf.io/card-mode?category=cloud-native-network&grouping=category
  - Tentative commit: https://github.com/skitt/landscape/commit/f13480a0de44e8d15570abceed164e0190d9e124
  - https://github.com/cncf/landscape/pull/2113

Not-required extras we've assigned ourselves:

- [ ] WIP: Security scanning
  - Will use to https://github.com/sonatype-nexus-community/nancy to provide in-CI and local security scanning
  - Also plan to track our real dependencies, and whenever a PR adds any, check that they don’t bring in their own security

**Comment by dfarrell07** [comment]
/me wonders if this should be an epic :thinking: It tracks many things like an epic, but it's due in less than one sprint.

**Comment by amye** [comment]
Yesss! It is kindof an epic but it'll go quick.

**Comment by dfarrell07** [comment]
@Oats87 Any update or timeline on the trademark agreement and domain transfer? Would also appreciate your review on https://github.com/submariner-io/submariner-website/pull/520. I think it's the last pending task for the open governance checkmark.

**Comment by dfarrell07** [comment]
I think we're basically done, as I understand it we only need:

* @thelinuxfoundation to accept our invite to be an Org Owner.
* @Oats87 to submit trademark docs.
* @Oats87 to send domain transfer.
* @Oats87 to review https://github.com/submariner-io/submariner-website/pull/520.

**Comment by Oats87** [comment]
@dfarrell07 I am currently in discussion with SUSE Legal over transfer of the trademark agreement. Unfortunately things aren't as "simple" as they used to be when we were independently Rancher.

Regarding the domain transfer, I am navigating the department within SUSE that is responsible for that as well.

**Comment by skitt** [comment]
Stacked logos added: https://github.com/cncf/artwork/pull/251 (this is what I used for the landscape PR).

**Comment by dfarrell07** [comment]
To update here, we're still waiting on SUSE to send the trademark transfer docs to the CNCF. I've been periodically pinging @Oats87 to check in, and he's been pinging SUSE Legal in turn. They are aware of the issue and seem to want to make progress, but clearly are not making good progress.

**Comment by amye** [comment]
Dropping a note here to cause activity and keep this open. ✨

**Comment by dfarrell07** [comment]
We're still periodically pinging Suse's legal team to check on this, they tell us it's still work-in-progress.

**Comment by amye** [comment]
Same thing out here :)

**Comment by skitt** [comment]
The trademarks were transferred.
