### ISSUE TITLE
Epic: submariner-addon

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner#1517]
This epic tracks work to be done on https://github.com/open-cluster-management/submariner-addon:

1. Repo infrastructure and mechanics
   * Use OCM.io dependencies instead of OCM: Depends on https://github.com/open-cluster-management/submariner-addon/issues/91
     * Addon-framework: Depends on https://github.com/open-cluster-management/submariner-addon/issues/92
     * API: Depends on https://github.com/open-cluster-management/submariner-addon/pull/94
   * Move the project from OCM to OCM.io (skitt): Depends on https://github.com/open-cluster-management-io/community/issues/69
   * Check permissions/code owners (help in #forum-acm-devops channel for org permissions; everything else can be handled by existing code owners)
     * Depends on https://github.com/openshift/release/pull/21197
     * Depends on https://github.com/openshift/release/pull/21496
   * Add linters and bots (in particular for CNCF compliance) (dfarrell)
     * DCO
       * Depends on https://github.com/openshift/release/pull/21160
     * Go linting
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/120
       * Depends on https://github.com/openshift/release/pull/21461
       * Depends on https://github.com/openshift/build-machinery-go/pull/54
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/144
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/150
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/135
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/155
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/165
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/170
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/172
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/171
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/173
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/174
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/175
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/176
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/178
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/179
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/180
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/181
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/182
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/183
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/187
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/190
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/191
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/192
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/193
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/195
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/196
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/197
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/194
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/199
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/200
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/201
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/202
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/205
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/203
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/210
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/211
       * Depends on https://github.com/open-cluster-management/submariner-addon/pull/212
       * Update golangci-lint version to be able to enable:
         * [ ] Depends on https://github.com/open-cluster-management/submariner-addon/pull/204
         * [ ] Depends on https://github.com/open-cluster-management/submariner-addon/pull/206
         * [ ] errname
         * [ ] importas (currently no violations reported)
         * [ ] promlinter (we don't use Prometheus in the add-on)
         * [ ] wastedassign (currently no violations reported)
       * Do we want these linters? Check the box if we want the linter, ~~strikethrough~~ if we don't want it. For checked linters, send a PR to fix/enable the linter. For ~~unwanted~~ linters, send a PR to document inline why we don't want the linter. Once there is a PR, remove the linter from the list here and add the PR to the list above.
         * [x] [goerr113](https://github.com/Djarvur/go-err113) [Janki] Check correlation with errcheck [dfarrell] goerr113 and errlint are similar, but errcheck is different. The latest I see is that [goerr113 and errlint have non-overlapping checks](https://github.com/Djarvur/go-err113/issues/18), so we may need to run both for now. I imagine they will deprecate one or the other in golangci-lint once there is a clear best-implementation, but we can leave a comment inline to note this as well.
         * [x] revive [dfarrell] Checking the issues it flags here: https://github.com/open-cluster-management/submariner-addon/pull/207
         * [x] wrapcheck
         * Why do staticcheck's custom initialisms not cause expected failures? See: https://github.com/dfarrell07/submariner/pull/44
     * License header linting
     * Dependency license linting
     * Commit message linting
     * YAML linting
       * Fix our YAML linting example (https://github.com/submariner-io/shipyard/pull/628 and fixes in each repo).
     * Shell linting or remove need for existing shell scripting
     * Markdown linting
     * Markdown links
     * Prow mergecommitblocker plugin (test if it's already working)
   * Add and/or complete unit tests (tpantelis)
   * Add e2e tests
   * Determine whether we want to use Shipyard: https://github.com/open-cluster-management/submariner-addon/pull/93
     * We can't use Shipyard as-is in Prow because Prow runs jobs in pods, and we can't start our shipyard-dapper-base container in a pod.
   * Branching/releasing (dfarrell)
     * Depends on https://github.com/openshift/release/pull/22322
     * Depends on https://github.com/open-cluster-management/submariner-addon/pull/159
     * Depends on https://github.com/openshift/release/pull/22513
2. Testing: add a job in Submariner to test with OCM (smattar)
   * https://github.com/submariner-io/shipyard/pull/599
   * https://github.com/submariner-io/submariner-operator/pull/1476
3. Deprecation of _SubmarinerConfig_ in favor of https://github.com/submariner-io/cloud-prepare (skitt)
   * Depends on https://github.com/open-cluster-management/submariner-addon/issues/101
   * Depends on https://github.com/open-cluster-management/submariner-addon/issues/121
   * Depends on https://github.com/submariner-io/cloud-prepare/pull/96
4. Integration logic itself - can we offload some of it to the Submariner Operator? Depends on https://github.com/open-cluster-management/submariner-addon/issues/123 (Janki)
5. Feature set/UX (e.g features which are available in Submariner/subctl but are not exposed in the addon side)
   * Support NAT traversal with _SubmarinerConfig_
   * Support load balancer mode (sridharg)
   * Support VXLAN connectivity (without NAT-T) (aswins)
   * Handle pre-existing gateway nodes: Depends on https://github.com/open-cluster-management/submariner-addon/issues/84
   * Handle VPC peering: Depends on https://github.com/open-cluster-management/submariner-addon/issues/83
   * Handle directly-reachable nodes: Depends on https://github.com/open-cluster-management/submariner-addon/issues/82
   * Automatically configure the infrastructure
   * Handle upgrades
   * Handle uninstallation
6. Make sure the documentation is updated with any changes made above
7. Document how to troubleshoot Submariner with OCM (_e.g._ how to run `subctl gather`)

**Comment by skitt** [comment]
@dfarrell07 could you expand the “linters and bots” section?

**Comment by nyechiel** [comment]
@skitt - we need to review the feature-set section. One thing that's missing in the list is VXLAN support, but there could be others.

**Comment by dfarrell07** [comment]
> Determine whether we want to use Shipyard

I think this is one of the first things we need to do, as how we want to add linting depends on what we decide.

I tend to think we should use Shipyard's infra.

**Comment by dfarrell07** [comment]
Continuing to think we should build on Shipyard. I'm struggling, getting a taste of how it would be without Shipyard, with duplicating the infra required to add basic gitlint CI.

The Makefile here as-is seems to require Go 1.15 for everything. The latest available from Ubuntu's package manager is 1.13, which why I'm having to install it manually.

https://github.com/dfarrell07/submariner-addon/pull/1

**Comment by skitt** [comment]
> Continuing to think we should build on Shipyard. I'm struggling, getting a taste of how it would be without Shipyard, with duplicating the infra required to add basic gitlint CI.

Right, that’s what I’m thinking too. My main concern is how well our Dapper-based builds will work with Prow; I reckon the best way to find that out would be to open a PR using Dapper ;-).

> The Makefile here as-is seems to require Go 1.15 for everything. The latest available from Ubuntu's package manager is 1.13, which why I'm having to install it manually.

We even need 1.16 for the build itself (see `go.mod`); Ubuntu 21.04 has everything required, as does Fedora 34 of course, but some mainstream distributions don’t (notably, Debian 11 will have Go 1.15, and RHEL 8.4 has 1.15).

**Comment by skitt** [comment]
> @skitt - we need to review the feature-set section. One thing that's missing in the list is VXLAN support, but there could be others.

I’ve added the missing pieces from the feature matrix (look at the last edit).

**Comment by dfarrell07** [comment]
> > The Makefile here as-is seems to require Go 1.15 for everything. The latest available from Ubuntu's package manager is 1.13, which why I'm having to install it manually.
> 
> We even need 1.16 for the build itself (see `go.mod`); Ubuntu 21.04 has everything required, as does Fedora 34 of course, but some mainstream distributions don’t (notably, Debian 11 will have Go 1.15, and RHEL 8.4 has 1.15).

I think we have Ubuntu 20.04 on the ubuntu-latest GHA runner.

https://github.com/actions/virtual-environments#available-environments

It seems to install 1.13.

> go version go1.13.8 linux/amd64

https://github.com/dfarrell07/submariner-addon/pull/2/checks?check_run_id=3253760648

> My main concern is how well our Dapper-based builds will work with Prow; I reckon the best way to find that out would be to open a PR using Dapper ;-)

I made a basic Shipyard Makefile/Dockerfile.dapper per the docs, which was going fine until I realized I had clobbered the existing Makefile. :sweat_smile: 

On a somewhat-related note, I just saved your custom-Dapper PR from stalebot. Has Mike's feedback been addressed? Can we merge it? https://github.com/submariner-io/shipyard/pull/594

**Comment by skitt** [comment]
> > > The Makefile here as-is seems to require Go 1.15 for everything. The latest available from Ubuntu's package manager is 1.13, which why I'm having to install it manually.
> > 
> > We even need 1.16 for the build itself (see `go.mod`); Ubuntu 21.04 has everything required, as does Fedora 34 of course, but some mainstream distributions don’t (notably, Debian 11 will have Go 1.15, and RHEL 8.4 has 1.15).
> 
> I think we have Ubuntu 20.04 on the ubuntu-latest GHA runner.
> 
> https://github.com/actions/virtual-environments#available-environments

Yes, runners only provide LTS releases of Ubuntu; the next update will be 22.04.

> On a somewhat-related note, I just saved your custom-Dapper PR from stalebot. Has Mike's feedback been addressed? Can we merge it? [submariner-io/shipyard#594](https://github.com/submariner-io/shipyard/pull/594)

I think it has, but I’d rather wait for Mike to take another look at it — there’s no rush. (And thanks for re-opening it!)

**Comment by skitt** [comment]
@SteveMattar would you be interested in working on adding an E2E test using OCM in Submariner? It should be similar to the work you’ve done to test the bundle with OLM. There’s already a “deploy” target in the addon which sets up kind with OLM and OCM.

**Comment by SteveMattar** [comment]
@skitt yes sure I will.

**Comment by dfarrell07** [comment]
We talked about moving away from vendoring today on the addon sync. In summary, it doesn't seem like vendoring is worth it. In particular: 

* Assurance of artifacts being what we expect can be provided by go.sum.
* Caching for temporary outages can be provided by goproxy.
* If a dependency were to really disappear (be deleted), we'd want to take action to move away from it anyway.

The costs to vendoring are substantial:

* ~100K LoC diffs when dependencies change.
* Git repo histoires include everything ever vendored, making the repo very large.
  * The k8s/k8s repo is 775.59 MiB.
  * The k8s/test-infra repo is 164.56 MiB.

**Comment by maayanf24** [comment]
@skitt Can we close this epic and track remaining work in new epic / issues?

**Comment by skitt** [comment]
Yes, let’s close this, it has run its course. Remaining tasks should be added to appropriate epics or handled as individual issues.
