### ISSUE TITLE
[Epic] Ensure Submariner works with dual-stack clusters with IPv4 connections

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#1739]
**What happened**:
Starting from K8s 1.23 version, it supports dual-stack K8s clusters where pods will get both IPv4 and IPv6 addresses. Submariner currently does not support IPv6, but it should atleast allow IPv4 communication to happen between the clusters.

- [x] [Skip IPv6 node addresses while adding fdb entries](https://github.com/submariner-io/submariner/pull/2245)
- [x] [Skip processing IPv6 addresses in mtu_handler](https://github.com/submariner-io/submariner/pull/2250)
- [x] [Submariner support for Dual Stack networks](https://github.com/submariner-io/submariner/pull/2294) Includes fixes in submariner-gateway pods, route-agent pods and mtu_handler.
- [x] [Support in SM Globalnet for dual-stack clusters](https://github.com/submariner-io/submariner/pull/2323)
- [x] [Support for deploying dual-stack k8s KIND clusters](https://github.com/submariner-io/shipyard/pull/1173) 
- [x] [Document dual-stack option in make command](https://github.com/submariner-io/submariner-website/pull/898)
- [x] [Dual-stack job in CI](https://github.com/submariner-io/shipyard/pull/1174)
- [x] [Release notes](https://github.com/submariner-io/submariner/pull/2327/files)

**Comment by sridhargaddam** [comment]
Related issue: https://github.com/submariner-io/submariner/issues/1546

**Comment by dfarrell07** [comment]
Relevant: https://github.com/submariner-io/submariner/issues/1546
