### ISSUE TITLE
Submariner support on air-gapped environments

### ISSUE THREAD

**Issue by nyechiel** [submariner-io/submariner#1790]
Running Kubernetes in air-gapped environments (i.e using offline private container registries and repositories without any access to the public Internet) seems to be a common request. The goal of this issue to assess Submariner's readiness to support such environments.

### Work items:
* [x] [Allow overriding the default image repository and version in subctl diagnose command](submariner-io/subctl#34)
* [x] [Subctl uninstall references an hard-coded image](https://github.com/submariner-io/submariner-operator/issues/2001)
* [x] [Make nettest image configurable in test framework](https://github.com/submariner-io/shipyard/pull/839)
* [x] [Support for air-gapped KIND environment](https://github.com/submariner-io/shipyard/pull/940)
* [x] [Air gapped support in Operator: Changes to submariner CR, config changes to submariner GW pod etc](https://github.com/submariner-io/submariner-operator/pull/2272)
* [x] [Changes in Submariner Gateway pod to avoid making API calls to public servers in air-gapped env](https://github.com/submariner-io/submariner/pull/2053)
* [x] [Support for specifying –air-gapped flag as part of join command](https://github.com/submariner-io/subctl/pull/299)
* [x] Allow overriding the public-ip of the Gateway node using the annotation on the GW node.
* [x] [Update SubmarinerConfig with airGappedDeployment flag](https://github.com/stolostron/submariner-addon/pull/524)
* [x] [Support for air-gapped KIND environment](https://github.com/submariner-io/shipyard/pull/940)
* [x] [Updates to upstream documentation](https://github.com/submariner-io/submariner-website/pull/838)
* [x] [Document how to deploy and use Submariner on Air-gapped clusters](https://github.com/submariner-io/submariner-website/issues/852)

## Acceptance Criteria
In an air-gapped environment, when using Submariner, the following requirements should be met

1. All Submariner pods in submariner-operator namespace should be running without any CrashloopBackoff/ImagePull errors.
2. The connections between all the clusters is successfully established.
3. All submariner e2e tests should be passing.
4. subctl diagnose should work fine without any errors.

## Definition of Done (Checklist)

Tasks:
* [x] Code complete (Dev)
* [x] Functionality working (Dev)

**Comment by nyechiel** [comment]
@cgruver @asanderson I'd love to get your feedback on this issue. Can you help us identify gaps that need to be addressed in order to improve Submariner's experience in air-gapped environments?

**Comment by skitt** [comment]
I suspect we should also ensure we list all the images we rely on at runtime somewhere in the documentation.

**Comment by sridhargaddam** [comment]
> I suspect we should also ensure we list all the images we rely on at runtime somewhere in the documentation.

And also provide an option to override the default image repository in various utilities.

**Comment by skitt** [comment]
> > I suspect we should also ensure we list all the images we rely on at runtime somewhere in the documentation.
> 
> And also provide an option to override the default image repository in various utilities.

Or ensure we consistently follow the overrides provided elsewhere ;-).

**Comment by asanderson** [comment]
I know we discussed this before, but I haven't been following if it was actually implemented, but first and foremost, an *air-gapped* distro that includes ALL images, dependencies, binaries, helm charts, etc. and installer as simple as K3s provides; see the following K3s air-gap install page for a great example:  https://rancher.com/docs/k3s/latest/en/installation/airgap.  AFAIC, just a master list of images and dependencies is nice, but building a distro of them all is ideal.

Otherwise, running all tests successfully in an air-gapped set up would be great, including subctl diagnose related tests.

**Comment by cgruver** [comment]
My really raw notes for installing in a disconnected environment are here:

https://github.com/cgruver/lab-multi-region/tree/main/submariner

From my perspective, if `--repository` and `--version` were universally honored by all of the `subctl` operations that require images, I think that would satisfy the needs of a disconnected install.

The node annotation `gateway.submariner.io/public-ip=dns:<FQDN>` takes care of the ipify.org dependency.  As noted, it needs better documentation.

I'm going to write a blog post about my disconnected install soon.

**Comment by cgruver** [comment]
FWIW, those notes above are very opinionated to my home lab setup.  So, if you try to follow along, you will want to reference the CLI that I wrote to maintain my lab:  https://upstreamwithoutapaddle.com/home-lab/labcli/

**Comment by nyechiel** [comment]
I feel like at this point the only remaining gap is docs.

**Comment by skitt** [comment]
See also https://github.com/kubernetes-sigs/kind/issues/2776

**Comment by dfarrell07** [comment]
Another user reported a relevant issue, need to check if it's something new or already covered: https://github.com/submariner-io/submariner/issues/1962

**Comment by nyechiel** [comment]
@sridhargaddam can you please update this issue?

**Comment by sridhargaddam** [comment]
> Another user reported a relevant issue, need to check if it's something new or already covered: #1962

It looks like a separate issue, I just reopened it and asked for additional logs.

**Comment by sridhargaddam** [comment]
> @sridhargaddam can you please update this issue?

Done. @nyechiel I think it might be useful to create a dedicated page on the website capturing the high level steps required for setting up clusters in Air-gapped deployments. We can also capture notes on how to run various commands like subctl verify/diagnose etc in the air-gapped setup.

**Comment by cgruver** [comment]
It's time for me to refresh my current install, so I'd be more than happy to test it out for you.

**Comment by dfarrell07** [comment]
This seems to have all the parts done now, so closing as done. Congrats all! :partying_face:
