### ISSUE TITLE
Investigate exporting Submariner metrics without needing to open ports

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner#1944]
Currently we need to open ports to access some Submariner metrics (at least those exported on a port on the host network).

We should look into some other way of exporting the metrics which doesn’t require this. One possible idea is to use `NodePort`.

**Work Items**
- [x] https://github.com/submariner-io/enhancements/pull/128
- [x] https://github.com/submariner-io/subctl/pull/212
- [x] https://github.com/submariner-io/submariner/pull/1967
- [x] https://github.com/submariner-io/submariner-operator/pull/2182
- [x] https://github.com/submariner-io/subctl/pull/228

**Comment by sridhargaddam** [comment]
Note: Currently we open the Metrics port (TCP/8080 and TCP/8081) only within the local cluster and not to the outside world. Using NodePort might solve the issue, but it can open the corresponding port globally which may not be what we want.

**Comment by vthapar** [comment]
@skitt @nyechiel Can we close this now, or when it becomes part of next milestone release?

**Comment by nyechiel** [comment]
> @skitt @nyechiel Can we close this now, or when it becomes part of next milestone release?

I think we can close it. This is fixed by: https://github.com/submariner-io/submariner-operator/pull/2182

@vthapar can you please make sure we track any docs changes (actual docs and release notes) separately?
