### ISSUE TITLE
Epic: enhancements to Globalnet Implementation, aka Globalnet v2

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#652]
**What would you like to be added**:
I'd like to propose an enhancement to the Globalnet implementation such that it is more scalable and we have more number of globalIps for Multi-cluster services.

**Current Implementation**

1. Globalnet supports only Pod to remoteService connectivity via globalIps.
2. Globalnet Controller annotates every Pod/Service in a cluster except for the ones in EXCLUDED_NAMESPACES
3. The globalIp annotations are translated to IPTable rules on the active Gateway Node of the cluster.
4. The annotation on the Pod is for egress traffic whereas the annotation on the Service is for ingress traffic.

**New Enhancement Proposal**
https://github.com/submariner-io/enhancements/blob/devel/submariner/globalnet-enhancement2-0.md

![globalnet-topology1](https://user-images.githubusercontent.com/6574656/117713405-4227b580-b1f3-11eb-9572-c2354b9b1772.png)

**Work Items**
- [x] 1. [Support creation of clientset, informers and listers for GlobalEgressIP CRD](https://github.com/submariner-io/submariner/issues/1157)
- [x] 2. [Register ClusterGlobalEgressIP, GlobalEgressIP and GlobalIngressIP CRDs](https://github.com/submariner-io/submariner/issues/1358)
- [x] 3. [Create clusterRoles for accessing Globalnet 2.0 CRDs](https://github.com/submariner-io/submariner-operator/issues/1114)
- [x] 4. [Support creation of clientset, informers and listers for GlobalIngressIP CRD](https://github.com/submariner-io/submariner/issues/1337)
- [x] 5. <del>[Provide configuration mechanism for default number of globalIPs at Cluster level](https://github.com/submariner-io/submariner-operator/issues/1116)</del>
- [x] 6. [Include ipset in Globalnet Image](https://github.com/submariner-io/submariner/pull/1339)
- [x] 7. [Support GlobalEgressIPs at the cluster level and program necessary egress rules.](https://github.com/submariner-io/submariner/issues/1163)
- [x] 8. [Support GlobalEgressIPs at namespace level.](https://github.com/submariner-io/submariner/issues/1164)
- [x] 9. [Support GlobalEgressIPs to Pods (or set of Pods) which has the highest precedence.](https://github.com/submariner-io/submariner/issues/1165)
- [x] 10. [Support Globalnet IngressIPs for exported Services.](https://github.com/submariner-io/submariner/issues/1404)
- [x] 11. [Support Headless Services and program ingress rules for the backend Pods.](https://github.com/submariner-io/submariner/issues/732)
- [x] 12. Implement necessary unit tests for each of the use-cases ([Datapath support for headless services](https://github.com/submariner-io/submariner/pull/1456) pending).
- [x] 13. [Implement necessary e2e tests to validate various use-cases.](https://github.com/submariner-io/submariner/issues/1167)
- [x] 14. [Update documentation.](https://github.com/submariner-io/submariner-website/issues/455)
- [x] 15. [Document how to upgrade from 0.8 release to the newer implementation.](https://github.com/submariner-io/submariner-website/issues/456)
- [x] 16. [Support allocation of a block of IPs in globalnet IPAM](https://github.com/submariner-io/submariner/issues/1347)
- [x] 17. [Add GlobalIngressIP controller to Lighthouse Agent](https://github.com/submariner-io/lighthouse/issues/551)
- [x] 18. [Add Globalnet Ingress and Service Export Controllers](https://github.com/submariner-io/submariner/pull/1390)
- [x] 19. [Support Globalnet with Headless services in Lighthouse](https://github.com/submariner-io/lighthouse/issues/558)
- [x] 20. [Lighthouse E2E changes for Globalnet v2 and headless services](https://github.com/submariner-io/lighthouse/issues/559)
- [x] 21. [Globalnet 2.0 Service Controller](https://github.com/submariner-io/submariner/pull/1413)
- [x] 22. [Support Gateway healthcheck in Globalnet 2.0](https://github.com/submariner-io/submariner/pull/1420)
- [x] 23. [Shipyard test_connection to use the new GlobalIngressIP Object](https://github.com/submariner-io/shipyard/pull/587)
- [x] 24. [Enable GN2.0 controllers and validate e2e clusteregress](https://github.com/submariner-io/submariner/pull/1424)
- [x] 25. [Operator: Use globalnet v2 enabled versions of submariner and lighthouse](https://github.com/submariner-io/submariner-operator/issues/1436)
- [x] 26. [Egress datapath support for Headless Service Pods](https://github.com/submariner-io/submariner/pull/1460)
- [x] 27. [Use 242.0.0.0/8 as default for GlobalnetCIDRRange and add validations for invalid CIDR ranges](https://github.com/submariner-io/submariner-operator/issues/1458)
- [x] 28. [Limit the max number of GlobalIPs to 20 for ClusterGlobalEgressIPs as well as GlobalEgressIP objects](https://github.com/submariner-io/submariner/pull/1451)
- [x] 29. [Reconcile any stale iptables/ipset rules for objects that were deleted when Globalnet Pod was down](https://github.com/submariner-io/submariner/pull/1457)
- [x] 30. [Optimize GlobalIngressIP retrieval in lighthouse (use informer cache)](https://github.com/submariner-io/lighthouse/pull/587)
- [x] 31. [Remove old submariner Globalnet code](https://github.com/submariner-io/submariner/pull/1470)
- [x] 32. [Enhance subctl gather to log the Globalnet2.0 objects](https://github.com/submariner-io/submariner-operator/pull/1495)
- [ ] 33. [Use event handler for Gateway monitor](https://github.com/submariner-io/submariner/issues/1331)
- [ ] 34. [Metrics support](https://github.com/submariner-io/submariner/issues/1471)
- [ ] 35. [Avoid dependency on the IPtable chains programmed by IPtables kube-proxy driver.](https://github.com/submariner-io/submariner/issues/1166)

**Comment by sridhargaddam** [comment]
@nyechiel @mangelajo @Oats87 @mkolesnik @vthapar @skitt @jds2001 @deanlorenz @roytman - Please take a look at this proposal and share your comments/feedback. Thank you.

**Comment by nyechiel** [comment]
bump

**Comment by tpantelis** [comment]
bump

**Comment by nyechiel** [comment]
@sridhargaddam if it makes sense, let's turn this one into an epic. I'll let you link and organize the different work items in here. Thanks!

**Comment by nyechiel** [comment]
@sridhargaddam I think we can close this at this point. There are individual work items which are tracked separately. Would you agree?

**Comment by sridhargaddam** [comment]
> @sridhargaddam I think we can close this at this point. There are individual work items which are tracked separately. Would you agree?

That's true @nyechiel. Number 34 and 35 are already getting addressed as part of ACM Globalnet support. Work item number 33 can be tracked separately. I'll close this, thanks.
