### ISSUE TITLE
Epic: support encryption-less connections between clusters

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner#674]
**What would you like to be added**:

Support for unencrypted connections between clusters.

**Why is this needed**:

All current cable drivers involve encrypting content, which is great for privacy but involves some overhead. On private connections, it would be useful to enable unencrypted connections, for example using IP-on-IP or VxLAN.

**Work items**:

- [x] Enhancement proposal: https://github.com/submariner-io/submariner/issues/1313
- [x] New cable driver : https://github.com/submariner-io/submariner/issues/1149
- [x] CI: https://github.com/submariner-io/submariner/issues/1148
- [x] Deployment (Operator, subctl) : https://github.com/submariner-io/submariner-operator/issues/1101
- [x] Deployment (helm) : https://github.com/submariner-io/submariner-charts/issues/116
- [x] Metrics : https://github.com/submariner-io/submariner/issues/1150
- [x] Docs: https://github.com/submariner-io/submariner-website/issues/450

**Comment by nyechiel** [comment]
Per further discussion, IPsec VPN without encryption is also a good option we should consider. This boils down to supporting different config options per cable driver which is a subset of submariner-io/enhancements#67

**Comment by nyechiel** [comment]
Per conversation with Paul Wouters (Libreswan maintainer), these are some options to consider:

1. Null encryption mode: https://github.com/libreswan/libreswan/tree/main/testing/pluto/ikev2-67-esp-null-iperf
2. Null encryption **and** null authentication mode: https://github.com/libreswan/libreswan/tree/main/testing/pluto/ikev2-algo-15-esp-null-none

Generally, with modern NICs/CPUs, setting ESP to null is not recommend; aes_gcm128 is the most efficient option, and should result in same throughput as esp-null. Here is the relevant GCP RFC for more context: https://tools.ietf.org/html/rfc4106

**Comment by nyechiel** [comment]
bump

**Comment by skitt** [comment]
This is still relevant.

**Comment by nyechiel** [comment]
- [ ] New cable driver
- [ ] CI: https://github.com/submariner-io/submariner/issues/1148
- [ ] Deployment (Operaror, Helm, subctl)
- [ ] Metrics
- [ ] Docs

**Comment by tpantelis** [comment]
bump
