### ISSUE TITLE
Epic: OVN support

### ISSUE THREAD

**Issue by nyechiel** [submariner-io/submariner#778]
Submariner is not compatible with OVN-based deployments at the moment. The request is to add support for interconnecting clusters that use the OVN (ovn-kubernetes) CNI plugin.

- [x] Submariner-OVN exploration: https://github.com/submariner-io/submariner/issues/793
- [x] Document the design via an enhancement proposal: https://github.com/submariner-io/enhancements/pull/11
- [x] Shipyard support for deploying OVN https://github.com/submariner-io/shipyard/issues/335
- [x] Improve the submariner-operator to pass down the network-plugin type down to the route-agent https://github.com/submariner-io/submariner-operator/issues/736
- [x] Improve the submariner-operator to start the network-plugin-syncer for plugins that need it (OVN for now).
- [x] Improve the submariner-operator to gather OVN credentials (for NB-DB and SB-DB and pass them down to the syncer)
- [x] Create the initial architecture/interface for the network-plugin drivers. https://github.com/submariner-io/submariner/issues/857
- [x] Convert the existing implementation into a "kube-proxy iptables" driver which will be the default. https://github.com/submariner-io/submariner/issues/858
- [x] Create the OVN Driver  https://github.com/submariner-io/submariner/issues/859
- [x] Create the network-plugin-syncer for OVN https://github.com/submariner-io/submariner/pull/943
- [ ] Globalnet support https://github.com/submariner-io/submariner/issues/383 
- [ ] Move all ovn handling to go-ovn, contribute any missing parts to go-ovn https://github.com/submariner-io/submariner/issues/1100 and fix go-ovn limitations for #1101 
- [ ] no destroy-recreate objects in ovn under updates https://github.com/submariner-io/submariner/issues/1101
- [x] Any documentation changes necessary regarding the architecture, or ovn details in http://submariner.io https://github.com/submariner-io/submariner-website/issues/304

**Comment by nyechiel** [comment]
@mangelajo do you see a reason to keep this Epic open? At this point, we can probably track the remaining gaps individually IMHO.

**Comment by skitt** [comment]
There is still some work to be done here.
