### ISSUE TITLE
cloud-prepare: automated infrastructure preparation

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner#873]
We currently maintain an AWS “preparation” script which is supposed to be run before `subctl`. How difficult would it be to provide the same functionality in `subctl`?

### Advantages:

* a seamless experience for `subctl` users (but not for operator users, unless we can extend the operator to take care of this too — perhaps using OpenShift operator dependency and the machine set operator)
* no dependency on Terraform, avoiding issues such as https://github.com/submariner-io/submariner/issues/847

### Disadvantages:

* this could creep into re-implementing a decent chunk of Terraform

Ideally this would be end up being a generic “platform preparation” feature, with support for different providers. But that can come later, once we have a couple of implementations (if we pursue this path).

### Work Items:

- [x] ~~Create cloud-prepare repository~~
- [x] [Add cloud-prepare repository to release process](https://github.com/submariner-io/releases/pull/126)
- [x] Add linting to the new cloud-prepare repository
- [x] [Implement basics of prepare/cleanup of AWS for Submariner](https://github.com/submariner-io/cloud-prepare/pull/2)
- [x] [Add `subctl` support for prepare/cleanup of AWS](https://github.com/submariner-io/submariner-operator/pull/1225)
- [x] [Add support for HA](https://github.com/submariner-io/cloud-prepare/pull/3)
- [x] [Improvement: Validation of pre-conditions on AWS](https://github.com/submariner-io/cloud-prepare/pull/4)
- [ ] Implement unit-tests for the prepare/cleanup on AWS
- [ ] Add website documentation on using the `subctl` commands

**Comment by nyechiel** [comment]
@mkolesnik has been looking at different alternatives, and it seems like the best way to move forward here is to provide a shared Go library which will be consumed by `subctl` and any other external tool (for e.g https://github.com/open-cluster-management/submariner-addon).

https://github.com/open-cluster-management/submariner-addon/blob/master/doc/submarinerConfig.md includes a proposed API for AWS; we should look at it and move it into the Submariner org, as well as look at adding support for other cloud providers. 

/cc @skeeey @zhiweiyin318 @qiujian16 @skitt

**Comment by skeeey** [comment]
If we have a shared Go library, it will be best, and we have implemented some code with aws-go-sdk in submariner-addon, https://github.com/open-cluster-management/submariner-addon/tree/master/pkg/cloud, and @zhiweiyin318 is investigating and implementing the azure part, you may refer to these implementations

**Comment by raffaelespazzoli** [comment]
I'd recommend addressing multiple cloud provider from the get go. At least Azure should also be supported immediately.

**Comment by qiujian16** [comment]
@nyechiel i think having a shared library hosted in submariner org and different tools could import it would make a lot of sense. We would love to have the discussion together about how interface should be defined and contribute to the library.

**Comment by nyechiel** [comment]
@mkolesnik now that our direction (Go library stored in `cloud-prepare`) is more clear, can you turn this Issue into an "Epic" and break it down into individual tasks we can track for 0.9?

**Comment by nyechiel** [comment]
I reported https://github.com/submariner-io/submariner-website/issues/503 and https://github.com/submariner-io/cloud-prepare/issues/17 to track the remaining items.
